# .github/workflows/ci.yaml
name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10] # Specify the versions of Python to test

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest tox tox-gh-actions

    - name: Test with tox
      run: tox

    # Step 4: Lint with flake8
    - name: Lint code with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # Step 5: Run tests
    - name: Run tests with pytest
      run: |
        pytest --cov=my_package tests/  # Adjust 'my_package' with your package name

    # Step 6: Upload coverage report
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: .coverage
